
spring:
  application:
    name: spoilage-service

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: default


#  datasource:
#    url: jdbc:mysql://localhost:3313/spoilage_db
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka