server:
  port: 8080

spring:
  application:
    name: api-gateway

  datasource:
    url: jdbc:mysql://localhost:3307/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: batch-service
          uri: lb://batch-service
          predicates:
            - Path=/batches/**

        - id: supplier-service
          uri: lb://supplier-service
          predicates:
            - Path=/suppliers/**

        - id: reorder-service
          uri: lb://reorder-service
          predicates:
            - Path=/reorders/**

        - id: qr-service
          uri: lb://qr-service
          predicates:
            - Path=/qr/**

        - id: spoilage-service
          uri: lb://spoilage-service
          predicates:
            - Path=/spoilage/**

        - id: location-service
          uri: lb://location-service
          predicates:
            - Path=/location/**

        - id: recall-service
          uri: lb://recall-service
          predicates:
            - Path=/recall/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

        - id: dashboard-service
          uri: lb://dashboard-service
          predicates:
            - Path=/dashboard/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka