spring:
  application:
    name: reorder-service

  config:
    import: optional:configserver:http://localhost:8888

  profiles:
    active: default

  jackson:
    time-zone: Asia/Colombo

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Colombo