package com.ecobite.auth_service.enums;

public enum Permission {


    PRODUCT_MODULE_ACCESS,
    SUPPLIER_MODULE_ACCESS,
    BATCH_MODULE_ACCESS,
    LOCATION_MODULE_ACCESS,
    QR_MODULE_ACCESS,
    USER_MANAGEMENT_ACCESS,

    PRODUCT_READ,
    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,
    PRODUCT_UPDATE_STOCK,

    SUPPLIER_READ,
    SUPPLIER_CREATE,
    SUPPLIER_UPDATE,
    SUPPLIER_DELETE,
    SUPPLIER_ASSIGN_PRODUCT,
    SUPPLIER_UPDATE_RATING,

    BATCH_READ,
    BATCH_CREATE,
    BATCH_UPDATE,
    BATCH_ALLOCATE,
    BATCH_SPOIL,
    BATCH_RECALL,

    LOCATION_READ,
    LOCATION_CREATE,
    LOCATION_ASSIGN_BATCH,
    LOCATION_MOVE_BATCH,

    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE
}
