version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: supplier_db
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: supplier_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: